Edit/test rule generator
ISG-ICS/QueryBooster pull request #17
Opened 2023-12-20 23:40 UTC by seongjinyoon

## Description
- Fixed wrong test assertions that had previously existed due to a bug from the previous `mo-sql-parsing` library version regarding `ILIKE`.
- Test cases 2 and 9 fixed.

2023-12-21 21:54 UTC, baiqiushi requested changes
Let's remove unnecesary changes.

2023-12-21 21:54 UTC, baiqiushi commented on server/wsgi.py
Why do we need to change this file in this PR?

2023-12-21 22:33 UTC, seongjinyoon commented on server/wsgi.py
My mistake. Resolved.

2024-01-13 00:04 UTC, baiqiushi approved these changes
LGTM.

2024-01-13 00:05 UTC, merged